sonar.projectKey=cyborg-nomade_cybernetic-mutualism
sonar.projectName=cybernetic-mutualism
sonar.sourceEncoding=UTF-8
sonar.sources=models,scripts
sonar.tests=tests
sonar.exclusions=models/antinomy/outputs/**
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
